### ISSUE TITLE
Rename the project to awesome-johnnydecimal?

### ISSUE THREAD

**Issue by lebriton** [johnnydecimal/awesome-johnnydecimal#3]
I suggest this project to be renamed into "awesome-johnnydecimal".

Awesome lists are a great way to gather interesting projects around a particular topic. [Have a look at the ginormous amount of these lists on GitHub.](https://github.com/topics/awesome)

I suggest this renaming to increase SEO. Because deep down, this list looks a lot like an awesome list.

**Comment by johnnydecimal** [comment]
😃
